---
title: "Popular cars in Massachusetts"
date: 2018-09-25
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE)

# Import libraries
library(knitr) 
library(dplyr)
library(tidyverse)
library(readr)
library(ggplot2)
library(sf)



# Imort tab delimited text file
cars <- read_tsv("../data/total active passenger plates for each county and town broken down by ma... (1).csv")

# clean up file
names(cars) <- c("county","city","manufacturer","model","total")
cars$city <- gsub("E BROOKFIELD","EAST BROOKFIELD",cars$city)
cars$city <- gsub("W BRIDGEWATER","WEST BRIDGEWATER",cars$city)

# Create unique identifier for each make and model of car - smashing together two separate columns into one.
cars$model <- str_squish(paste(cars$manufacturer," ",cars$model)) 

# caclulate the statewide totals by model
statewide_model_totals <- group_by(cars,model) %>%  
  summarize(total=sum(total),percent=sum(total)/sum(cars$total)*100) %>% 
  mutate(rank = order(order(total, decreasing=TRUE))) %>% 
  arrange(rank)

# caclulate the statewide totals by make
statewide_make_totals <- group_by(cars,manufacturer) %>%  
  summarize(total=sum(total),percent=sum(total)/sum(cars$total)*100) %>% 
  mutate(rank = order(order(total, decreasing=TRUE))) %>% 
  arrange(rank)


# Calculate the total number of cars in each city
car_city <- group_by(cars,city) 
city_totals <- summarize(car_city,city_total=sum(total)) 

# Calculate the total number of auto makes by city
make <- group_by(cars,county,city,manufacturer)
make2 <- summarize(make,make_total=sum(total))

# Then join the two tables to calculate the percentage of car makes in each city
cars_make <- left_join(city_totals, make2, by = "city" )
cars_make$make_percent <- round((cars_make$make_total / cars_make$city_total *100),digits=2)
#cars_make$make_percent< - round(cars_make$make_percent, digits=2)

# Rename car make columns and save file
cars_make<- select(cars_make,county,city,manufacturer,total=make_total,percent=make_percent,city_total)

# Calculate the percentage of car models in each city
car_model <- left_join(city_totals, cars, by = "city" )
car_model$percent <- car_model$total / car_model$city_total *100
car_model$percent<- round(car_model$percent, digits=2)

# Rename columns of model file and save file
car_model <-select(car_model,county,city,model,total,percent,city_total) #,city_total



# Calculate the rankings
# --- First gave the most popular car and the top 10 cars in each city
top_model<- car_model %>% group_by(city) %>% top_n(1, total)
top_ten<- car_model %>% group_by(city) %>% top_n(10, total)

# Then rank most popular models in each city 
top_ten<- top_ten %>%
  group_by(city) %>%
  mutate(rank = order(order(total, decreasing=TRUE)))
top_ten<- top_ten %>% arrange(city,desc(total))

# Then come up with the full ranking of all models in every city
rank_models<- car_model %>%
  group_by(city) %>%
  mutate(rank = order(order(total, decreasing=TRUE)))
rank_models<- rank_models %>% arrange(city,desc(total))


# Calculate the most popular car makes by city
top_make<- cars_make %>% group_by(city) %>% top_n(1, total)
top_ten_make<- cars_make %>% group_by(city) %>% top_n(10, total)
top_ten_make<- top_ten_make %>%
  group_by(city) %>%
  mutate(rank = order(order(total, decreasing=TRUE)))
top_ten_make<- top_ten_make %>% arrange(city,desc(total))


# Then come up with the full ranking of all makes in every city
rank_make<- cars_make %>%
  group_by(city) %>%
  mutate(rank = order(order(total, decreasing=TRUE)))
rank_make<- rank_make %>% arrange(city,desc(total))


# Find the top car in Nantucket (Jeep Wrangler)
top_ten_nantucket <- filter(top_ten, city == "NANTUCKET" & rank == 1)

# Find the top town for Mercedes (Weston)
top_town_mercedes <- filter(rank_make, manufacturer == "MERZ") %>% arrange(rank) %>% head(1)

# Find the top 10 cars in Boston (Accord and Camry are #1 and #2 respectively)
top_ten_boston <- filter(top_ten, city == "BOSTON") %>% ungroup() %>%  select(model,percent,rank) 


# Find number of Ferraris in Boston (35)
ferraris_boston <- filter(rank_make, city == "BOSTON",manufacturer == "FERR") 

# Find # of Plymouths  in Boston (55)
plymouth_boston <- filter(rank_make, city == "BOSTON",manufacturer == "PLYM" |manufacturer == "PLYMO") %>% summarize(cars = sum(total))


# Find # of Plymouth Valients in Boston (2)
plymouth_valient <- filter(rank_models, city == "BOSTON")  %>% filter(grepl('PLYM.*VAL', model)) %>% summarize(valients = sum(total))



# Find the top 3 makes in Boston (Toyota and Honda are #1 and #2 respectively)
top_makes_boston <- filter(rank_make, city == "BOSTON") %>% 
  head(3) %>% 
  ungroup() %>%  
  select(manufacturer,percent,rank) 


# Find the top 10 cars in Revere (Accord and Camry are #1 and #2 respectively)
top_ten_revere <- filter(top_ten, city == "REVERE") %>% 
  ungroup() %>%  
  select(model,percent,rank) 


# Find top cars in Berkshire County by town
berkshire <- filter(rank_models, county == "BERKSHIRE",rank==1) %>% arrange(city)

# Berkshire towns where Chev Silverado  is No. 1
# "ADAMS"  "CHESHIRE"  "CLARKSBURG"  "FLORIDA"  "HINSDALE" "LANESBOROUGH", 
#"LEE"  "OTIS" PERU"   "SAVOY"   "SHEFFIELD"    "WASHINGTON"  
# "WINDSOR" 
berkshire_chev <- filter(berkshire,model == "CHEV SILVER") %>% arrange(city)

# Berkshire towns where Subaru Forrester  is No. 1 
# (Becket, Egremont, Great Barrington, Lenox, Monterey, Mount Washington, 
# New Marlborough, Stockbridge, West Stockbridge)
berkshire_subaru <- filter(berkshire,model == "SUBA FOREST") %>% arrange(city)


# Berkshire towns where Subaru Outback  is No. 1  (Alford, Richmond, Sandisfield, Tyringham, Williamstown)
berkshire_outback <- filter(berkshire,model == "SUBA OUTBAC")  %>% arrange(city)

#Number of towns in Massachusetts where Subaru Forrester is ranked No. 1 (20)
mass_subaru <- filter(rank_models,model == "SUBA FOREST",rank==1) %>% nrow()

# town that has one dominant car (Nantucket, where Jeep Wranglers account for 11.4% of cars)
mass_dominant <- filter(rank_models,rank==1,city_total>100) %>% arrange(-percent) %>%  head(3) %>%  ungroup %>%  select(city,model,total,percent)

# town that is second dominant car (Lawrence, where Honda Accord accounts for 9.7% of cars)

# town where one manufacturer dominates
# Lawrence (Honda) is No. 1
# Wellfleet, Eastham, Orleans (Toyota) rank 2-4.
mass_dominant_make <- filter(rank_make,rank==1,city_total>100) %>% arrange(-percent) %>% head(4)  %>% ungroup() %>%  select(city,manufacturer,total,percent,rank)


# Top manufacturers statewide (Toyota with 17.7%)
statewide_make_head<- head(statewide_make_totals,10)


# Top models statewide (Toyota Camry with nearly 4%)
statewide_model_head <- head(statewide_model_totals,10)

# Find number of towns that have some of the top cars
number_one_car <- filter(rank_models,rank==1) %>% select (city,model) %>% group_by(model) %>% count(model) %>% arrange(-n) %>% rename(number_of_towns = n)  %>% head(6)


# Find towns where Toyota Tacoma dominates 
# Includes Essex in Cape Ann and a number of towns on Cape Cod
# such as Proncetown, Chilmark, Wellfleet and Truro.
toyota_tacoma <- filter(rank_models, model=="TOYT TACOMA",rank==1) %>% arrange(city)

# Find towns where Toyota Prius dominates - 9 towns, including Amherst and Northampton, Lincoln, and Carlisle
toyota_prius <- filter(rank_models, model=="TOYT PRIUS",rank==1) %>% arrange(city)


#Find the five most popular cars in Cambridge
top_five_cambridge <- filter(top_ten, city == "CAMBRIDGE") %>% head(5) %>% ungroup() %>%  select(model,percent,rank) 



# Find towns where Mercedes dominates - Weston is number one, followed by Dover, Lynnfield, and Wellesley
top_towns_mercedes <- filter(rank_make, manufacturer == "MERZ") %>% arrange(rank) %>% head(5) %>% ungroup() %>%  select(city,percent,rank) 


# Find towns where BMW dominates - Weston is number one, followed by Dover, Wellesley, Sudbury, and Manchester-by-the-sea
top_towns_bmw <- filter(rank_make, manufacturer == "BMW") %>% arrange(-percent) %>% head(5) %>% ungroup() %>%  select(city,percent,rank) 


# Find towns where Tesla dominates - Weston is number one, followed by Dover, Wellesley, Lincoln and Carlisle.
# Concord, Sherborn, Brookline, Lexington, and Wayland
top_towns_tesla <- filter(rank_make, manufacturer == "TESL") %>% arrange(-percent) %>% head(10)  %>% ungroup() %>%  select(city,total,percent,rank)

#Find the 10 most popular cars in Weston # Honda CRV is No 1, followed by Jeep Wrangler. BMW X5 comes in third
top_ten_weston <- filter(top_ten, city == "WESTON") %>% head(10)  %>% ungroup() %>%  select(model,total,percent,rank)

# load Massachusetts town map 
shape_file <- "../gis/TOWNSSURVEY_POLY.shp"
mass <- st_read(shape_file)
ggplot(mass) + geom_sf()
mass <- mass %>% mutate_if(is.factor, as.character) 

```

There were `r formatC(sum(cars$total),format="d",big.mark=",")` private passenger cars and light-trucks registered in Massachusetts in 2018, according to data from the state Registry of Motor Vehicles.

We used the data for a (http://apps.bostonglobe.com/metro/graphics/2018/09/cars-by-town/ "Boston Globe story.")
Billy wrote the story. I analyzed the data. And Patrick Garvin created the graphics on the Boston Globe site.


```{R}
##map cars by manufacturer
mass_dominant_make_map <- filter(rank_make,rank==1)
make_map <- left_join(mass_dominant_make_map, mass,
                          by=c("city"="TOWN"))

ggplot(make_map) +
  geom_sf(aes(fill=manufacturer)) +
  labs(title="Most popular car make by town", caption="Source: RMV") +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank())

#map cars by model
mass_dominant_model <- filter(rank_models,rank==1)
models_map <- left_join(mass_dominant_model, mass,
                      by=c("city"="TOWN"))

ggplot(models_map) +
  geom_sf(aes(fill=model)) +
  labs(title="Most popular car model by town", caption="Source: RMV") +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank())

```

The most popular car in Nantucket is `r top_ten_nantucket$model`.

Mercedes is the most popular car manufacturer in this town: `r top_town_mercedes$city`.

The top 10 cars in Boston are: `r kable(top_ten_boston)`

The top 10 cars in Revere are: `r kable(top_ten_revere)`

The top 3 makes in Boston are `r kable(top_makes_boston)`

There are `r ferraris_boston$total` Ferraris registered in Boston. There are also `r plymouth_boston$cars` Plymouths, including `r plymouth_valient$valients` Plymouth Valients.


```{R}

#map cars by model in Berkshire County
berkshire_dominant_model <- filter(mass_dominant_model,county=="BERKSHIRE")
berkshire_map <- inner_join(berkshire_dominant_model, mass,
                      by=c("city"="TOWN"))

ggplot(berkshire_map) +
  geom_sf(aes(fill=model)) +
  labs(title="Most popular car model by town in Berkshire County", caption="Source: RMV") +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank())

```

These are the Berkshire County towns where the Chevrolet Silverado is tops:
`r berkshire_chev$city`

These are the Berkshire County towns where the Subaru Forrester is tops:
`r berkshire_subaru$city`

These are the Berkshire County towns where the Subaru Outback is tops:
`r berkshire_outback$city`

These are number of towns where Subaru Forrester is tops:
`r mass_subaru`

And these are the cars that dominate specific cars:
`r kable(mass_dominant)`

In, `r mass_dominant$city[1]`, the `r mass_dominant$model[1]` dominates, accounting for `r mass_dominant$percent[1]` of the town's cars.

Close behind in `r mass_dominant$city[2]`,  the `r mass_dominant$model[2]` makes up `r mass_dominant$percent[2]` of the city's vehicles.

These models are popular in lots of towns
`r kable(number_one_car)`

Here are towns where one manufacturer dominates:
`r kable(mass_dominant_make)`

Here are the top manufacturers statewide:
`r kable(statewide_make_head)`

Here are the top models statewide:
`r kable(statewide_model_head)`

These are the towns where the Toyota Tacoma is the popular vehicle: 
`r toyota_tacoma$city`

The Toyota Prius is the most popular car in `r nrow(toyota_prius)` towns:
`r toyota_prius$city` # name of towns

Here are the top five most popular cars in Cambridge: 
`r kable(top_five_cambridge)`

And here are the top 10 most popular cars in Weston
`r kable(top_ten_weston)`

Here are the top five towns where Mercedes is the most popular:
`r kable(top_towns_mercedes)`

Here are the top five towns for BMWs:
`r kable(top_towns_bmw)`

Here are the top five towns for Tesla:
`r kable(top_towns_tesla)`



